<a href="https://colab.research.google.com/github/MuhammadAwais9092/programming-assignment/blob/main/Practise%20work/%208th%20December%20Untitled68.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
#Arrays practise

car=['BMW','Mercedes','ferrari','Lamborghini']
print(car[2])
car.append("Nissan")
print(car)
car.insert(2,"Toyota")
print(car)
car.pop(1)
print(car)
car.pop()
print(car)
car.remove("BMW")
print(car)
del car[1]
print(car)
car.sort()
print(car)
sorted(car)
print(car)
car.reverse()
print(car)
L=len(car)
print(L)
car.clear()
print(car)

ferrari
['BMW', 'Mercedes', 'ferrari', 'Lamborghini', 'Nissan']
['BMW', 'Mercedes', 'Toyota', 'ferrari', 'Lamborghini', 'Nissan']
['BMW', 'Toyota', 'ferrari', 'Lamborghini', 'Nissan']
['BMW', 'Toyota', 'ferrari', 'Lamborghini']
['Toyota', 'ferrari', 'Lamborghini']
['Toyota', 'Lamborghini']
['Lamborghini', 'Toyota']
['Lamborghini', 'Toyota']
['Toyota', 'Lamborghini']
2
[]


In [30]:
import numpy as np
number=np.array((1,2,3,4,5))
print(number)

[1 2 3 4 5]


In [31]:
import numpy as np
number=np.array([[1,2,3,4],[5,6,7,8]])
print(number)

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
import numpy as np
number=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(number)
print('The number of dimensions are: ',number.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
The number of dimensions are:  3


In [67]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *
import ColabTurtle.Turtle as t
initializeTurtle()
t.color('red')
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [61]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *
import ColabTurtle.Turtle as t
initializeTurtle()

side_length=100
angle=360/4

for i in range(4):
  forward(side_length)
  right(angle)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [69]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *
import ColabTurtle.Turtle as t
initializeTurtle()
t.color('blue')

t.forward(140)
t.left(90)
t.forward(70)
t.left(90)
t.forward(140)
t.left(90)
t.forward(70)
t.left(90)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [68]:
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *
import ColabTurtle.Turtle as t
initializeTurtle()
t.color('green')

t.forward(100)  
t.left(120)
t.forward(100)
t.left(120)
t.forward(100)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
